name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Roda todo dia Ã  meia-noite
  workflow_dispatch: # Permite rodar manualmente
push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Fesisp
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/Boa_Vista
